Models/tb_student.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fyp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_student
    {
        public string s_id { get; set; }
        public string s_acadprogID { get; set; }
        public string s_svID { get; set; }
        public Nullable<int> s_proposalD { get; set; }
    
        public virtual tb_acadprog tb_acadprog { get; set; }
        public virtual tb_proposal tb_proposal { get; set; }
        public virtual tb_sv tb_sv { get; set; }
        public virtual tb_user tb_user { get; set; }
    }
}

Controllers/tb_studentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using fyp1.Models;

namespace fyp1.Controllers
{
    public class tb_studentController : Controller
    {
        private fyp1dbEntities db = new fyp1dbEntities();

        // GET: tb_student
        public ActionResult Index()
        {
            //for committee view
            if (@Session["UserType"].ToString() == "2")
            {
                var ID = Session["UserID"].ToString();
                var tb_student = db.tb_student.Include(t => t.tb_sv).Include(t => t.tb_svstatus).Include(t => t.tb_user).Where(t => t.s_id == ID);
                return View(tb_student);
            }
            if (@Session["UserType"].ToString() == "3")
            {
                var ID = Session["UserID"].ToString();
                var tb_student = db.tb_student.Include(t => t.tb_sv).Include(t => t.tb_svstatus).Include(t => t.tb_user).Where(t => t.s_svID == ID).Where(t => t.s_svstatus != 3);
                return View(tb_student);
            }
            //for student view
            else
            {
                var ID = Session["AcadProg"].ToString();
                var tb_student = db.tb_student.Include(t => t.tb_sv).Include(t => t.tb_svstatus).Include(t => t.tb_user).Where(t => t.tb_user.u_acadProgID == ID);
                return View(tb_student.ToList());
            }

          
            //var tb_student = db.tb_student.Include(t => t.tb_proposal).Include(t => t.tb_sv).Include(t => t.tb_user);
            //return View(tb_student.ToList());
        }

        // GET: tb_student/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_student tb_student = db.tb_student.Find(id);
            if (tb_student == null)
            {
                return HttpNotFound();
            }
            return View(tb_student);
        }

        // GET: tb_student/Create
        public ActionResult Create()
        {
            ViewBag.s_acadprogID = new SelectList(db.tb_acadprog, "ap_ID", "ap_desc");
            ViewBag.s_proposalD = new SelectList(db.tb_proposal, "p_ID", "p_studentID");
            ViewBag.s_svID = new SelectList(db.tb_sv, "sv_ID", "sv_ID");
            ViewBag.s_id = new SelectList(db.tb_user, "u_ID", "u_name");
            var clients = db.tb_sv
                .Select(s => new
                {
                    Text = s.sv_ID + " - " + s.tb_user.u_name,
                    Value = s.sv_ID
                })
                .ToList();

            ViewBag.s_svID = new SelectList(clients, "Value", "Text");
            return View();
        }

        // POST: tb_student/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "s_id,s_svID,s_svstatus")] tb_student tb_student)
        {
            if (ModelState.IsValid)
            {
                db.tb_student.Add(tb_student);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.s_svID = new SelectList(db.tb_sv, "sv_ID", "sv_ID", tb_student.s_svID);
            ViewBag.s_id = new SelectList(db.tb_user, "u_ID", "u_name", tb_student.s_id);
            return View(tb_student);
        }

        // GET: tb_student/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_student tb_student = db.tb_student.Find(id);
            if (tb_student == null)
            {
                return HttpNotFound();
            }
            ViewBag.s_svstatus = new SelectList(db.tb_svstatus, "svst_id", "svst_desc", tb_student.s_svstatus);
            return View(tb_student);
        }

        // POST: tb_student/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "s_id,s_svID,s_svstatus")] tb_student tb_student)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tb_student).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.s_svID = new SelectList(db.tb_sv, "sv_ID", "sv_ID", tb_student.s_svID);
            ViewBag.s_id = new SelectList(db.tb_user, "u_ID", "u_name", tb_student.s_id);
            ViewBag.s_svstatus = new SelectList(db.tb_svstatus, "svst_id", "svst_desc", tb_student.s_svstatus);
            return View(tb_student);
        }

        // GET: tb_student/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_student tb_student = db.tb_student.Find(id);
            if (tb_student == null)
            {
                return HttpNotFound();
            }
            return View(tb_student);
        }

        // POST: tb_student/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            tb_student tb_student = db.tb_student.Find(id);
            db.tb_student.Remove(tb_student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }



        // GET: tb_student/Edit/5
        public ActionResult selectSV(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_student tb_student = db.tb_student.Find(id);
            if (tb_student == null)
            {
                return HttpNotFound();
            }
            ViewBag.s_id = new SelectList(db.tb_user, "u_ID", "u_name", tb_student.s_id);

            var clients = db.tb_sv.Where(t=>t.tb_user.u_acadProgID==tb_student.tb_user.u_acadProgID)
                .Select(s => new
                {
                    Text = s.sv_ID + " - " + s.tb_user.u_name,
                    Value = s.sv_ID
                })
                .ToList();

            ViewBag.s_svID = new SelectList(clients, "Value", "Text", tb_student.s_svID);
            return View(tb_student);
        }

        // POST: tb_student/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult selectSV([Bind(Include = "s_id,s_svID,s_svstatus")] tb_student tb_student)
        {
            if (ModelState.IsValid)
            {
                tb_student.s_svstatus = 1;
                db.Entry(tb_student).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.s_svID = new SelectList(db.tb_sv, "sv_ID", "sv_ID", tb_student.s_svID);
            ViewBag.s_id = new SelectList(db.tb_user, "u_ID", "u_name", tb_student.s_id);
            return View(tb_student);
        }

        // GET: tb_student/Details/5
        public ActionResult Agreement(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_student tb_student = db.tb_student.Find(id);
            if (tb_student == null)
            {
                return HttpNotFound();
            }
            return View(tb_student);
        }
    }
}

Views/tb_student/Agreement.cshtml
@model fyp1.Models.tb_student
@{
    ViewBag.Title = "Agreement";
    Layout = "";
}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>FYP System</title>
    <link rel="stylesheet" href="~/Content/Style2.css">
    <link rel="license" href="https://www.opensource.org/licenses/mit-license/">
    <script src="~/Scripts/script.js"></script>
    <!-- Custom fonts for this template-->
    <link href="~/Theme/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/Theme/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body>
    <div class="row justify-content-center pb-5">
        <div class="well col-xs-10 col-sm-10 col-md-3 " >
            <button onclick="window.print()" id="printPageButton"><i style="font-size:24px" class="fas fa-print"></i></button>
        </div>
    </div>

    <div class="row justify-content-center">
        <img src="~/Theme/utm.png"class="img" alt="Responsive image">
    </div>
    <div class="row justify-content-center">
        <h2>FYP1 AGREEMENT BETWEEN STUDENT & SUPERVISOR</h2>
    </div>

    <div class="row justify-content-center">
        <div class="well col-xs-10">
            <div style="text-align:center">
                <address>
                    <br />STUDENT DETAILS<br />
                    Student ID: @Html.DisplayFor(model => model.s_id) <br>
                    Student Name: @Html.DisplayFor(model => model.tb_user.u_name)<br>
                    Student Email : @Html.DisplayFor(model => model.tb_user.u_email) <br>
                    Student Contact No :@Html.DisplayFor(model => model.tb_user.u_contact) <br>
                    <br><br>
                </address>
                <address>
                    SUPERVISOR DETAILS<br />
                    Supervisor ID: @Html.DisplayFor(model => model.s_svID) <br>
                    Supervisor Name: @Html.DisplayFor(model => model.tb_sv.tb_user.u_name)<br>
                    Supervisor Email : @Html.DisplayFor(model => model.tb_sv.tb_user.u_email) <br>
                    Supervisor Contact No :@Html.DisplayFor(model => model.tb_sv.tb_user.u_contact) <br>
                    <br><br>
                </address>
                <address>
                    Regular review from supervisors will ensure that students execute their project according to the faculty’s procedure and standards,<br />
                    as well as the project objectives and aims. Student must arrange a minimum of six (6) formal meetings with their supervisors before<br />
                    receiving permission to submit and present their project. However, students are strongly advised to arrange a weekly meeting with the<br />
                    supervisors to address issues related to project execution. All meetings must be recorded in a logbook and the supervisor’s <br />
                    signature of approval of each meeting is required. The logbook form is available at the PSM website.
                </address>

            </div>

        </div>

    </div>

</body>

Views/tb_student/Create.cshtml
@model fyp1.Models.tb_student

@{
    ViewBag.Title = "Student Registration";
}

<h2>Student Registration</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.s_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("s_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.s_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.s_svID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("s_svID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.s_svID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/tb_student/Delete.cshtml
@model fyp1.Models.tb_student

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.s_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.s_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_user.u_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_user.u_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.s_svID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.s_svID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" onclick="return confirm('Are you sure?')"/> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/tb_student/Details.cshtml
@model fyp1.Models.tb_student

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.s_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.s_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_user.u_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_user.u_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_user.u_acadProgID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_user.u_acadProgID) - 
            @Html.DisplayFor(model => model.tb_user.tb_acadprog.ap_desc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.s_svID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.s_svID) - 
            @Html.DisplayFor(model => model.tb_sv.tb_user.u_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.s_svstatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_svstatus.svst_desc)
        </dd>


    </dl>
</div>
<p>

    @if (Session["UserType"].ToString() == "2")
    {
        @Html.ActionLink("Edit", "selectSV", new { id = Model.s_id })
    }

    @Html.ActionLink("Back to List", "Index")
</p>

Views/tb_student/Edit.cshtml
@model fyp1.Models.tb_student

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.s_id)
    @Html.HiddenFor(model => model.s_svID)

    <div class="form-group">
        @Html.LabelFor(model => model.s_svstatus, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("s_svstatus", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.s_svstatus, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-success" onclick="return confirm('Are you sure?')" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/tb_student/Index.cshtml
@model IEnumerable<fyp1.Models.tb_student>

@{
    ViewBag.Title = "Student Record";
}
@if (Session["UserType"].ToString() == "2")
{
    <h2>Student's Supervisor Application </h2>
}
else
{
    <h2>Student Record</h2>
}
<table class="table" id="prettify">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.s_id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.tb_user.u_name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.tb_user.u_email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.s_svID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.s_svstatus)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.s_id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tb_user.u_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tb_user.u_email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.s_svID) -
                    @Html.DisplayFor(modelItem => item.tb_sv.tb_user.u_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tb_svstatus.svst_desc)
                </td>
                <td>
                    @if (Session["UserType"].ToString() == "5")
                    {
                        @Html.ActionLink("Status", "Edit", new { id = item.s_id }, new { @class = "btn btn-warning" })
                        @*@Html.ActionLink("Delete", "Delete", new { id = item.s_id }, new { @class = "btn btn-danger" })*@
                    }
                    @Html.ActionLink("Details", "Details", new { id = item.s_id }, new { @class = "btn btn-info" })
                    @if (Session["UserType"].ToString() == "2")
                    {
                        @Html.ActionLink("Select Supervisor", "selectSV", "tb_student", new { id = item.s_id }, new { @class = "btn btn-primary" })
                    }

                    @if (item.s_svstatus.ToString() == "2" && (Session["UserType"].ToString() == "2" || Session["UserType"].ToString() == "3"))
                    {
                        @Html.ActionLink("View Agreement", "Agreement", "tb_student", new { id = item.s_id }, new { @class = "btn btn-warning", @target = "_blank" })
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

Views/tb_student/selectSV.cshtml
@model fyp1.Models.tb_student

@{
    ViewBag.Title = "Select Supervisor";
}

<h2>Select Supervisor</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.s_id)

        <div class="form-group">
            @Html.LabelFor(model => model.s_svID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("s_svID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.s_svID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" onclick="return confirm('Are your sure?')"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}